# Generated by Django 3.0 on 2020-06-30 11:42

from django.db import migrations, transaction
from l10n_cuba.data.codigos_postales import get_municipio


def populate(apps, schema_editor):
    if schema_editor.connection.alias != 'default':
        return

    CodigoPostal = apps.get_model('l10n_cuba', 'CodigoPostal')
    m = get_municipio(apps=apps)

    CODIGOS_POSTALES = [
        # Pinar del Rio
        {'municipality': m['Sandino'], 'zip_code': 24150, 'place': None},
        {'municipality': m['Mantua'], 'zip_code': 22200, 'place': None},
        {'municipality': m['Minas de Matahambre'], 'zip_code': 22300, 'place': None},
        {'municipality': m['Viñales'], 'zip_code': 22400, 'place': None},
        {'municipality': m['La Palma'], 'zip_code': 22600, 'place': None},
        {'municipality': m['Los Palacios'], 'zip_code': 22900, 'place': None},
        {'municipality': m['Consolación del Sur'], 'zip_code': 23000, 'place': None},
        {'municipality': m['Pinar del Río'], 'zip_code': 20100, 'place': None},
        {'municipality': m['San Luis'], 'zip_code': 23100, 'place': None},
        {'municipality': m['San Juan y Martínez'], 'zip_code': 23200, 'place': None},
        {'municipality': m['Guane'], 'zip_code': 23300, 'place': None},

        # Artemisa
        {'municipality': m['Bahía Honda'], 'zip_code': 22600, 'place': None},
        {'municipality': m['Mariel'], 'zip_code': 32100, 'place': None},
        {'municipality': m['Guanajay'], 'zip_code': 32200, 'place': None},
        {'municipality': m['Caimito'], 'zip_code': 32300, 'place': None},
        {'municipality': m['Bauta'], 'zip_code': 32400, 'place': None},
        {'municipality': m['San Antonio de los Baños'], 'zip_code': 32500, 'place': None},
        {'municipality': m['Güira de Melena'], 'zip_code': 33600, 'place': None},
        {'municipality': m['Alquízar'], 'zip_code': 33700, 'place': None},
        {'municipality': m['Artemisa'], 'zip_code': 33800, 'place': None},
        {'municipality': m['Candelaria'], 'zip_code': 22700, 'place': None},
        {'municipality': m['San Cristóbal'], 'zip_code': 22800, 'place': None},

        # La Habana
        {'municipality': m['Playa'], 'zip_code': 11300, 'place': None},
        {'municipality': m['Plaza de la Revolución'], 'zip_code': 10400, 'place': None},
        {'municipality': m['Centro Habana'], 'zip_code': 10200, 'place': None},
        {'municipality': m['La Habana Vieja'], 'zip_code': 10100, 'place': None},
        {'municipality': m['Regla'], 'zip_code': 11200, 'place': None},
        {'municipality': m['La Habana del Este'], 'zip_code': 10900, 'place': None},
        {'municipality': m['Guanabacoa'], 'zip_code': 11100, 'place': None},
        {'municipality': m['San Miguel del Padrón'], 'zip_code': 11000, 'place': None},
        {'municipality': m['Diez de Octubre'], 'zip_code': 10700, 'place': None},
        {'municipality': m['Diez de Octubre'], 'zip_code': 10500, 'place': None},
        {'municipality': m['Cerro'], 'zip_code': 10600, 'place': None},
        {'municipality': m['Marianao'], 'zip_code': 11500, 'place': None},
        {'municipality': m['La Lisa'], 'zip_code': 17100, 'place': None},
        {'municipality': m['Boyeros'], 'zip_code': 10800, 'place': None},
        {'municipality': m['Arroyo Naranjo'], 'zip_code': 10900, 'place': None},
        {'municipality': m['Cotorro'], 'zip_code': 14000, 'place': None},

        # Mayabeque
        {'municipality': m['Bejucal'], 'zip_code': 32600, 'place': None},
        {'municipality': m['San José de las Lajas'], 'zip_code': 32700, 'place': None},
        {'municipality': m['Jaruco'], 'zip_code': 32800, 'place': None},
        {'municipality': m['Santa Cruz del Norte'], 'zip_code': 32900, 'place': None},
        {'municipality': m['Madruga'], 'zip_code': 33000, 'place': None},
        {'municipality': m['Nueva Paz'], 'zip_code': 33100, 'place': None},
        {'municipality': m['San Nicolás'], 'zip_code': 33200, 'place': None},
        {'municipality': m['Güines'], 'zip_code': 33900, 'place': None},
        {'municipality': m['Batabanó'], 'zip_code': 33400, 'place': None},
        {'municipality': m['Quivicán'], 'zip_code': 33500, 'place': None},
        {'municipality': m['Melena del Sur'], 'zip_code': 33300, 'place': None},

        # Matanzas
        {'municipality': m['Matanzas'], 'zip_code': 40100, 'place': None},
        {'municipality': m['Cárdenas'], 'zip_code': 42110, 'place': None},
        {'municipality': m['Cárdenas'], 'zip_code': 42200, 'place': 'Varadero'},  # Varadero
        {'municipality': m['Martí'], 'zip_code': 42300, 'place': None},
        {'municipality': m['Colón'], 'zip_code': 42400, 'place': None},
        {'municipality': m['Perico'], 'zip_code': 42500, 'place': None},
        {'municipality': m['Jovellanos'], 'zip_code': 42600, 'place': None},
        {'municipality': m['Pedro Betancourt'], 'zip_code': 42700, 'place': None},
        {'municipality': m['Limonar'], 'zip_code': 42800, 'place': None},
        {'municipality': m['Unión de Reyes'], 'zip_code': 42900, 'place': None},
        {'municipality': m['Ciénaga de Zapata'], 'zip_code': 43000, 'place': None},
        {'municipality': m['Jagüey Grande'], 'zip_code': 43100, 'place': None},
        {'municipality': m['Calimete'], 'zip_code': 43200, 'place': None},
        {'municipality': m['Los Arabos'], 'zip_code': 43300, 'place': None},

        # Villa Clara
        {'municipality': m['Corralillo'], 'zip_code': 52100, 'place': None},
        {'municipality': m['Quemado de Güines'], 'zip_code': 52200, 'place': None},
        {'municipality': m['Sagua la Grande'], 'zip_code': 53310, 'place': None},
        {'municipality': m['Encrucijada'], 'zip_code': 52400, 'place': None},
        {'municipality': m['Camajuaní'], 'zip_code': 52500, 'place': None},
        {'municipality': m['Caibarién'], 'zip_code': 52610, 'place': None},
        {'municipality': m['Remedios'], 'zip_code': 52700, 'place': None},
        {'municipality': m['Placetas'], 'zip_code': 52800, 'place': None},
        {'municipality': m['Santa Clara'], 'zip_code': 50100, 'place': None},
        {'municipality': m['Cifuentes'], 'zip_code': 52900, 'place': None},
        {'municipality': m['Santo Domingo'], 'zip_code': 53100, 'place': None},
        {'municipality': m['Ranchuelo'], 'zip_code': 53100, 'place': None},
        {'municipality': m['Manicaragua'], 'zip_code': 53200, 'place': None},

        # Cienfuegos
        {'municipality': m['Abreus'], 'zip_code': 57700, 'place': None},
        {'municipality': m['Aguada de Pasajeros'], 'zip_code': 57100, 'place': None},
        {'municipality': m['Cienfuegos'], 'zip_code': 55100, 'place': None},
        {'municipality': m['Cruces'], 'zip_code': 57500, 'place': None},
        {'municipality': m['Cumanayagua'], 'zip_code': 57600, 'place': None},
        {'municipality': m['Lajas'], 'zip_code': 57400, 'place': None},
        {'municipality': m['Palmira'], 'zip_code': 57300, 'place': None},
        {'municipality': m['Rodas'], 'zip_code': 57200, 'place': None},

        # Sancti Spiritus
        {'municipality': m['Yaguajay'], 'zip_code': 62100, 'place': None},
        {'municipality': m['Jatibonico'], 'zip_code': 62200, 'place': None},
        {'municipality': m['Taguasco'], 'zip_code': 62300, 'place': None},
        {'municipality': m['Cabaiguán'], 'zip_code': 62410, 'place': None},
        {'municipality': m['Fomento'], 'zip_code': 62500, 'place': None},
        {'municipality': m['Trinidad'], 'zip_code': 62600, 'place': None},
        {'municipality': m['Sancti Spíritus'], 'zip_code': 60100, 'place': None},
        {'municipality': m['La Sierpe'], 'zip_code': 62700, 'place': None},

        # Ciego de Avila
        {'municipality': m['Chambas'], 'zip_code': 67100, 'place': None},
        {'municipality': m['Morón'], 'zip_code': 67210, 'place': None},
        {'municipality': m['Bolivia'], 'zip_code': 67300, 'place': None},
        {'municipality': m['Primero de Enero'], 'zip_code': 67400, 'place': None},
        {'municipality': m['Ciro Redondo'], 'zip_code': 67500, 'place': None},
        {'municipality': m['Florencia'], 'zip_code': 67600, 'place': None},
        {'municipality': m['Majagua'], 'zip_code': 67700, 'place': None},
        {'municipality': m['Ciego de Ávila'], 'zip_code': 65100, 'place': None},
        {'municipality': m['Venezuela'], 'zip_code': 67800, 'place': None},
        {'municipality': m['Baraguá'], 'zip_code': 67900, 'place': None},

        # Camaguey
        {'municipality': m['Carlos Manuel de Céspedes'], 'zip_code': 72100, 'place': None},
        {'municipality': m['Carlos Manuel de Céspedes'], 'zip_code': 74100, 'place': 'Piedrecitas'},  # Piedrecitas
        {'municipality': m['Carlos Manuel de Céspedes'], 'zip_code': 74110, 'place': 'República Dominicana'},  # República Dominicana
        {'municipality': m['Esmeralda'], 'zip_code': 72200, 'place': None},
        {'municipality': m['Esmeralda'], 'zip_code': 74120, 'place': 'Brasil'},  # Brasil
        {'municipality': m['Esmeralda'], 'zip_code': 74130, 'place': 'Jiquí'},  # Jiquí
        {'municipality': m['Esmeralda'], 'zip_code': 74140, 'place': 'Lombillo'},  # Lombillo
        {'municipality': m['Esmeralda'], 'zip_code': 74150, 'place': 'Tabor'},  # Tabor
        {'municipality': m['Esmeralda'], 'zip_code': 74170, 'place': 'Donato'},  # Donato
        {'municipality': m['Sierra de Cubitas'], 'zip_code': 72300, 'place': None},
        {'municipality': m['Sierra de Cubitas'], 'zip_code': 74180, 'place': 'Sierra de Cubitas'},  # Sierra de Cubitas
        {'municipality': m['Sierra de Cubitas'], 'zip_code': 74190, 'place': 'La Gloria'},  # La Gloria
        {'municipality': m['Minas'], 'zip_code': 72400, 'place': None},
        {'municipality': m['Minas'], 'zip_code': 72400, 'place': 'Senado'},  # Senado
        {'municipality': m['Minas'], 'zip_code': 72400, 'place': 'La Gabriela'},  # La Gabriela
        {'municipality': m['Minas'], 'zip_code': 72400, 'place': 'Lugareño'},  # Lugareño
        {'municipality': m['Minas'], 'zip_code': 72400, 'place': 'Redención'},  # Redención
        {'municipality': m['Nuevitas'], 'zip_code': 72510, 'place': None},
        {'municipality': m['Nuevitas'], 'zip_code': 72510, 'place': 'Nuevitas 1'},  # Nuevitas 1
        {'municipality': m['Nuevitas'], 'zip_code': 72520, 'place': 'Nuevitas 2'},  # Nuevitas 2
        {'municipality': m['Nuevitas'], 'zip_code': 72530, 'place': 'Nuevitas 3'},  # Nuevitas 3
        {'municipality': m['Nuevitas'], 'zip_code': 74250, 'place': 'Playa Santa Lucía'},  # Playa Santa Lucía
        {'municipality': m['Nuevitas'], 'zip_code': 74260, 'place': 'Puerto tarafa'},  # Puerto tarafa
        {'municipality': m['Nuevitas'], 'zip_code': 74270, 'place': 'Termoeléctrica 10 de Octubre'},  # Termoeléctrica 10 de Octubre
        {'municipality': m['Sibanicú'], 'zip_code': 72700, 'place': None},
        {'municipality': m['Sibanicú'], 'zip_code': 74370, 'place': 'Najasa'},  # Najasa
        {'municipality': m['Sibanicú'], 'zip_code': 74380, 'place': 'Hatuey'},  # Hatuey
        {'municipality': m['Sibanicú'], 'zip_code': 74390, 'place': 'Siboney'},  # Siboney
        {'municipality': m['Sibanicú'], 'zip_code': 74400, 'place': 'Patricio Lumumba'},  # Patricio Lumumba
        {'municipality': m['Florida'], 'zip_code': 72810, 'place': None},
        {'municipality': m['Florida'], 'zip_code': 72810, 'place': 'Florida 1'},  # Florida 1
        {'municipality': m['Florida'], 'zip_code': 72820, 'place': 'Florida 2'},  # Florida 2
        {'municipality': m['Florida'], 'zip_code': 72830, 'place': 'Florida 3'},  # Florida 3
        {'municipality': m['Florida'], 'zip_code': 74420, 'place': 'Agramonte'},  # Agramonte
        {'municipality': m['Florida'], 'zip_code': 74430, 'place': 'La Vallita'},  # La Vallita
        {'municipality': m['Florida'], 'zip_code': 74440, 'place': 'La Tomatera'},  # La Tomatera
        {'municipality': m['Florida'], 'zip_code': 74450, 'place': 'San Antonio'},  # San Antonio
        {'municipality': m['Camagüey'], 'zip_code': 70100, 'place': None},
        {'municipality': m['Camagüey'], 'zip_code': 70200, 'place': None},
        {'municipality': m['Camagüey'], 'zip_code': 74100, 'place': 'Altagracia'},  # Altagracia
        {'municipality': m['Vertientes'], 'zip_code': 72900, 'place': None},
        {'municipality': m['Vertientes'], 'zip_code': 74460, 'place': 'Aguilar'},  # Aguilar
        {'municipality': m['Vertientes'], 'zip_code': 74470, 'place': 'Los ángeles'},  # Los ángeles
        {'municipality': m['Vertientes'], 'zip_code': 74480, 'place': 'Batalla de las Guásimas'},  # Batalla de las Guásimas
        {'municipality': m['Jimaguayú'], 'zip_code': 73000, 'place': None},
        {'municipality': m['Jimaguayú'], 'zip_code': 74490, 'place': 'Contramaestre'},  # Contramaestre
        {'municipality': m['Jimaguayú'], 'zip_code': 74500, 'place': 'Rescate de Sanguily'},  # Rescate de Sanguily
        {'municipality': m['Santa Cruz del Sur'], 'zip_code': 73200, 'place': None},
        {'municipality': m['Santa Cruz del Sur'], 'zip_code': 74510, 'place': 'Cándido González'},  # Cándido González
        {'municipality': m['Santa Cruz del Sur'], 'zip_code': 74520, 'place': 'Haití'},  # Haití
        {'municipality': m['Santa Cruz del Sur'], 'zip_code': 74530, 'place': 'Cuatro Compañeros'},  # Cuatro Compañeros
        {'municipality': m['Santa Cruz del Sur'], 'zip_code': 74540, 'place': 'Jagua Tres'},  # Jagua Tres
        {'municipality': m['Santa Cruz del Sur'], 'zip_code': 74680, 'place': 'La Jagua'},  # La Jagua
        {'municipality': m['Guáimaro'], 'zip_code': 72600, 'place': None},
        {'municipality': m['Guáimaro'], 'zip_code': 74290, 'place': 'Camalote'},  # Camalote
        {'municipality': m['Guáimaro'], 'zip_code': 74300, 'place': 'Cascorro'},  # Cascorro
        {'municipality': m['Guáimaro'], 'zip_code': 74310, 'place': 'Nuevo Palo Seco'},  # Nuevo Palo Seco
        {'municipality': m['Guáimaro'], 'zip_code': 74320, 'place': 'Galbis'},  # Galbis
        {'municipality': m['Guáimaro'], 'zip_code': 74330, 'place': 'Martí'},  # Martí
        {'municipality': m['Guáimaro'], 'zip_code': 74340, 'place': 'Palo Seco'},  # Palo Seco
        {'municipality': m['Guáimaro'], 'zip_code': 74350, 'place': 'Santa Lucía'},  # Santa Lucía
        {'municipality': m['Guáimaro'], 'zip_code': 74360, 'place': 'San Miguel de Bagá'},  # San Miguel de Bagá
        {'municipality': m['Najasa'], 'zip_code': 73100, 'place': None},
        {'municipality': m['Najasa'], 'zip_code': 73100, 'place': 'Cuatro Caminos'},  # Cuatro Caminos

        # Las Tunas
        {'municipality': m['Manatí'], 'zip_code': 77100, 'place': None},
        {'municipality': m['Puerto Padre'], 'zip_code': 77200, 'place': None},
        {'municipality': m['Jesús Menéndez'], 'zip_code': 77300, 'place': None},
        {'municipality': m['Majibacoa'], 'zip_code': 77400, 'place': None},
        {'municipality': m['Las Tunas'], 'zip_code': 75500, 'place': None},
        {'municipality': m['Las Tunas'], 'zip_code': 75100, 'place': None},
        {'municipality': m['Jobabo'], 'zip_code': 77500, 'place': None},
        {'municipality': m['Colombia'], 'zip_code': 77600, 'place': None},
        {'municipality': m['Amancio'], 'zip_code': 77700, 'place': None},

        # Holguin
        {'municipality': m['Gibara'], 'zip_code': 82100, 'place': None},
        {'municipality': m['Gibara'], 'zip_code': 84140, 'place': 'Velasco'},  # Velasco
        {'municipality': m['Rafael Freyre'], 'zip_code': 83300, 'place': None},
        {'municipality': m['Banes'], 'zip_code': 82300, 'place': None},
        {'municipality': m['Antilla'], 'zip_code': 82400, 'place': None},
        {'municipality': m['Báguanos'], 'zip_code': 82500, 'place': None},
        {'municipality': m['Holguín'], 'zip_code': 80100, 'place': None},
        {'municipality': m['Calixto García'], 'zip_code': 82600, 'place': None},
        {'municipality': m['Calixto García'], 'zip_code': 82600, 'place': 'Buena Ventura'},  # Buena Ventura
        {'municipality': m['Cacocum'], 'zip_code': 57200, 'place': None},
        {'municipality': m['Urbano Noris'], 'zip_code': 82800, 'place': None},
        {'municipality': m['Urbano Noris'], 'zip_code': 82800, 'place': 'San Germán'},  # San Germán
        {'municipality': m['Cueto'], 'zip_code': 82900, 'place': None},
        {'municipality': m['Mayarí'], 'zip_code': 83000, 'place': None},
        {'municipality': m['Frank País'], 'zip_code': 83100, 'place': None},
        {'municipality': m['Sagua de Tánamo'], 'zip_code': 83200, 'place': None},
        {'municipality': m['Moa'], 'zip_code': 83300, 'place': None},

        # Granma
        {'municipality': m['Río Cauto'], 'zip_code': 87100, 'place': None},
        {'municipality': m['Cauto Cristo'], 'zip_code': 87200, 'place': None},
        {'municipality': m['Jiguaní'], 'zip_code': 87300, 'place': None},
        {'municipality': m['Bayamo'], 'zip_code': 85100, 'place': None},
        {'municipality': m['Yara'], 'zip_code': 87400, 'place': None},
        {'municipality': m['Manzanillo'], 'zip_code': 87510, 'place': None},
        {'municipality': m['Campechuela'], 'zip_code': 87600, 'place': None},
        {'municipality': m['Media Luna'], 'zip_code': 87700, 'place': None},
        {'municipality': m['Niquero'], 'zip_code': 87800, 'place': None},
        {'municipality': m['Pilón'], 'zip_code': 87900, 'place': None},
        {'municipality': m['Bartolomé Masó'], 'zip_code': 88000, 'place': None},
        {'municipality': m['Buey Arriba'], 'zip_code': 88100, 'place': None},
        {'municipality': m['Guisa'], 'zip_code': 88200, 'place': None},

        # Santiago de Cuba
        {'municipality': m['Contramaestre'], 'zip_code': 92100, 'place': None},
        {'municipality': m['Mella'], 'zip_code': 92200, 'place': None},
        {'municipality': m['San Luis'], 'zip_code': 92300, 'place': None},
        {'municipality': m['Segundo Frente'], 'zip_code': 92100, 'place': None},
        {'municipality': m['Songo - La Maya'], 'zip_code': 92610, 'place': None},
        {'municipality': m['Santiago de Cuba'], 'zip_code': 90100, 'place': None},
        {'municipality': m['Palma Soriano'], 'zip_code': 92610, 'place': None},
        {'municipality': m['Tercer Frente'], 'zip_code': 92700, 'place': None},
        {'municipality': m['Guamá'], 'zip_code': 92800, 'place': None},

        # Guantanamo
        {'municipality': m['El Salvador'], 'zip_code': 97100, 'place': None},
        {'municipality': m['Manuel Tames'], 'zip_code': 97700, 'place': None},
        {'municipality': m['Yateras'], 'zip_code': 99420, 'place': None},
        {'municipality': m['Baracoa'], 'zip_code': 97310, 'place': None},
        {'municipality': m['Maisí'], 'zip_code': 99320, 'place': None},
        {'municipality': m['Imías'], 'zip_code': 97500, 'place': None},
        {'municipality': m['San Antonio del Sur'], 'zip_code': 97600, 'place': None},
        {'municipality': m['Caimanera'], 'zip_code': 97800, 'place': None},
        {'municipality': m['Guantánamo'], 'zip_code': 95100, 'place': None},
        {'municipality': m['Niceto Pérez'], 'zip_code': 97900, 'place': None},

        # Isla de la Juventud
        {'municipality': m['Isla de la Juventud'], 'zip_code': 25100, 'place': None},
        {'municipality': m['Isla de la Juventud'], 'zip_code': 25300, 'place': None},
    ]
    with transaction.atomic():
        for codigos_postales in CODIGOS_POSTALES:
            cp = CodigoPostal.objects.create(
                municipality=codigos_postales['municipality'],
                zip_code=codigos_postales['zip_code'],
                place=codigos_postales['place']
            )
            cp.save()


def reverse_populate(apps, schema_editor):
    CodigoPostal = apps.get_model('l10n_cuba', 'CodigoPostal')
    codigos_postales = CodigoPostal.objects.all()
    codigos_postales.delete()


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('l10n_cuba', '0004_codigopostal'),
    ]

    operations = [
        migrations.RunPython(populate, reverse_populate)
    ]
