# Generated by Django 3.2.3 on 2021-10-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l10n_cuba', '0005_populate_table_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopostal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
